### ISSUE TITLE
Crashes on startup of HA 2023.5.2

### ISSUE THREAD

**Issue by jaypi95-sc** [IATkachenko/HA-SleepAsAndroid#51]
### Home Assistant
**Version: 2023.5.2**
**Installation method** (according to [instructions](https://www.home-assistant.io/installation/)):
[X] Operating System
[ ] Linux VM
[ ] Container
[ ] Supervised
[ ] Core
### Integration

**Installation method:**
[X] HACS
[ ] manual from release
[ ] manual from git
**Integration version: 1.9.2** 
**Root topic: SleepAsAndroid** 
### Application settings

**topic: SleepAsAndroid/%%%device%%%**
[X] I can see MQTT messages from application at MQTT-server
## How it works now?
MQTT Messages arrive but nothing happens because integration is not loaded.
## What do you expect?
Integration should get loaded correctly
## Steps to reproduce
 1. Upgrade to 2023.5.2
 1. Observer error
 1. ???
 1. No profit
## Debug log
```
2023-05-08 08:14:06.193 INFO (MainThread) [custom_components.sleep_as_android] Setting up 40986c100e0ebc908eea6859744826ee 
2023-05-08 08:14:06.193 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry SleepAsAndroid for sleep_as_android
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/sleep_as_android/__init__.py", line 42, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, [Platform.SENSOR])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
2023-05-08 08:14:28.929 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'sleep_tracking_started', 'id': 'sleep_tracking_started'}
2023-05-08 08:14:28.929 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'sleep_tracking_stopped', 'id': 'sleep_tracking_stopped'}
2023-05-08 08:14:28.930 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'sleep_tracking_paused', 'id': 'sleep_tracking_paused'}
2023-05-08 08:14:28.933 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'sleep_tracking_resumed', 'id': 'sleep_tracking_resumed'}
2023-05-08 08:14:28.933 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'alarm_snooze_clicked', 'id': 'alarm_snooze_clicked'}
2023-05-08 08:14:28.933 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'alarm_snooze_canceled', 'id': 'alarm_snooze_canceled'}
2023-05-08 08:14:28.933 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'time_to_bed_alarm_alert', 'id': 'time_to_bed_alarm_alert'}
2023-05-08 08:14:28.934 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'alarm_alert_start', 'id': 'alarm_alert_start'}
2023-05-08 08:14:28.934 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'alarm_alert_dismiss', 'id': 'alarm_alert_dismiss'}
2023-05-08 08:14:28.934 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'alarm_skip_next', 'id': 'alarm_skip_next'}
2023-05-08 08:14:28.934 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'show_skip_next_alarm', 'id': 'show_skip_next_alarm'}
2023-05-08 08:14:28.934 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'rem', 'id': 'rem'}
2023-05-08 08:14:28.934 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'smart_period', 'id': 'smart_period'}
2023-05-08 08:14:28.935 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'before_smart_period', 'id': 'before_smart_period'}
2023-05-08 08:14:28.935 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'lullaby_start', 'id': 'lullaby_start'}
2023-05-08 08:14:28.935 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'lullaby_stop', 'id': 'lullaby_stop'}
2023-05-08 08:14:28.935 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'lullaby_volume_down', 'id': 'lullaby_volume_down'}
2023-05-08 08:14:28.935 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'deep_sleep', 'id': 'deep_sleep'}
2023-05-08 08:14:28.935 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'light_sleep', 'id': 'light_sleep'}
2023-05-08 08:14:28.936 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'awake', 'id': 'awake'}
2023-05-08 08:14:28.936 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'not_awake', 'id': 'not_awake'}
2023-05-08 08:14:28.936 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'apnea_alarm', 'id': 'apnea_alarm'}
2023-05-08 08:14:28.936 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'antisnoring', 'id': 'antisnoring'}
2023-05-08 08:14:28.936 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'sound_event_snore', 'id': 'sound_event_snore'}
2023-05-08 08:14:28.937 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'sound_event_talk', 'id': 'sound_event_talk'}
2023-05-08 08:14:28.937 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'sound_event_cough', 'id': 'sound_event_cough'}
2023-05-08 08:14:28.937 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'sound_event_baby', 'id': 'sound_event_baby'}
2023-05-08 08:14:28.937 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'sound_event_laugh', 'id': 'sound_event_laugh'}
2023-05-08 08:14:28.938 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'before_alarm', 'id': 'before_alarm'}
2023-05-08 08:14:28.938 DEBUG (MainThread) [custom_components.sleep_as_android.device_trigger] Got subscription to trigger: {'platform': 'device', 'domain': 'sleep_as_android', 'device_id': '0a36bcd493898618cc9f841fe0ae21e5', 'type': 'before_alarm'}
2023-05-08 08:14:48.083 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry SleepAsAndroid for sleep_as_android
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/sleep_as_android/__init__.py", line 42, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, [Platform.SENSOR])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms
```

## Additional information
Last working HA version: 2023.4.5
I updated directly from there so I can't say if it broke on 2023.5 or one of the point releases.

I'm currently at work but I will see if I can find anything else later in the day.

**Comment by IATkachenko** [comment]
`async_setup_platforms` is deprecated since `2022.12` and should be replaced by `async_forward_entry_setup` long time ago...
Sorry for this.
Fix will be available in few hours.

**Comment by IATkachenko** [comment]
My bad. It was fixed while refactoring (sic!) commit and missed in release notes.
Could you update to v1.10.0?

**Comment by IATkachenko** [comment]
Welcome!
Previous version of release notes did not contain any critical information, so `v1.10.0` looked like unnecessary update. So I'm not surprised that this update was missed.
