### ISSUE TITLE
Failure to Process New Event Type

### ISSUE THREAD

**Issue by Silvenga** [IATkachenko/HA-SleepAsAndroid#62]
### Home Assistant
**Version:**
**Installation method** (according to [instructions](https://www.home-assistant.io/installation/)):
[ ] Operating System
[ ] Linux VM
[X] Container
[ ] Supervised
[ ] Core
### Integration

**Installation method:**
[X] HACS
[ ] manual from release
[ ] manual from git
**Integration version:** 
**Root topic:** 
### Application settings

**topic:**
[ ] I can see MQTT messages from application at MQTT-server
## Steps to reproduce

After upgrading to SleepAsAndroid 20231001 there appears to be a new event type that's causing the custom component to fail. 

## Debug log
```
2023-10-13 21:02:31.873 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'SleepAsAndroid/Pixel 8 Pro': '{"event":"Unknown"}'

Traceback (most recent call last):

  File "/config/custom_components/sleep_as_android/__init__.py", line 253, in message_received

    target_sensor.process_message(msg)

  File "/config/custom_components/sleep_as_android/sensor.py", line 156, in process_message

    if self.state != new_state:

       ^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 569, in state

    raise ValueError(

ValueError: Sensor sensor.sleepasandroid_pixel_8_pro provides state value 'alarm_rescheduled', which is not in the list of options provided
```
## Additional information

I'm not sure, but it appears the filter for events in SleepAsAndroid doesn't work.

**Comment by Gibletron** [comment]
Have the same issue, and the PR fixes it for me

**Comment by IATkachenko** [comment]
@Gibletron, thx.
No it is not Android-specific, just the application update.
