### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by SkytAsul** [IATkachenko/HA-SleepAsAndroid#77]
### Home Assistant
**Version:** Core 2024.12.1, Supervisor 2024.11.4
**Installation method** (according to [instructions](https://www.home-assistant.io/installation/)):
[x] Operating System
[ ] Linux VM
[ ] Container
[ ] Supervised
[ ] Core
### Integration

**Installation method:**
[x] HACS
[ ] manual from release
[ ] manual from git
**Integration version:** 2.3.0
**Root topic:** sorry what?
### Application settings

**topic:** `alarm/SleepAsAndroid/%%%device%%%`
[x] I can see MQTT messages from application at MQTT-server
## How it works now?
 
```
2024-12-09 16:34:22.141 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up sleep_as_android platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/sleep_as_android/sensor.py", line 50, in async_setup_entry
    await instance.subscribe_root_topic(async_add_entities)
  File "/config/custom_components/sleep_as_android/__init__.py", line 292, in subscribe_root_topic
    self._subscription_state = await subscribe_2022_03(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/sleep_as_android/__init__.py", line 262, in subscribe_2022_03
    result = subscription.async_prepare_subscribe_topics(
        hass=_hass,
        new_state=_state,
        topics=_topic,
    )
TypeError: async_prepare_subscribe_topics() got an unexpected keyword argument 'new_state'. Did you mean 'sub_state'?
```
## What do you expect?

It should work haha
## Steps to reproduce
 1. step-1
 1. step-2
 1. ...
## Debug log
```
Put Home Assistant debug log, related to the issue, here
```

**Comment by SkytAsul** [comment]
Oops really sorry, I'm not similar with HA version scheme and thought it was something else. My apologies
