### ISSUE TITLE
Error log home assistant 2024.12.3 with integration 2.3.1 maybe with recent fix #79

### ISSUE THREAD

**Issue by Metus88** [IATkachenko/HA-SleepAsAndroid#80]
### Home Assistant
**Version:**2024.12.3
**Installation method** (according to [instructions](https://www.home-assistant.io/installation/)):
[ ] Operating System
[ ] Linux VM
[x] Container
[ ] Supervised
[ ] Core
### Integration

**Installation method:**
[x] HACS
[ ] manual from release
[ ] manual from git
**Integration version:** 2.3.1
**Root topic:** 
### Application settings

**topic:**
[x] I can see MQTT messages from application at MQTT-server
## How it works now?
 It works, but there is a ERROR in the log.
## What do you expect?

No log ERROR
## Steps to reproduce
 1. Use Home assistant 2024.12.3
 1. Via HACS install the integration 2.3.1
 1. ...
## Debug log
```
ERROR (MainThread) [homeassistant.components.sensor] Error while setting up sleep_as_android platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/sleep_as_android/sensor.py", line 50, in async_setup_entry
    await instance.subscribe_root_topic(async_add_entities)
  File "/config/custom_components/sleep_as_android/__init__.py", line 314, in subscribe_root_topic
    self._subscription_state = await subscribe_2022_03(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/sleep_as_android/__init__.py", line 278, in subscribe_2022_03
    result = subscription.async_prepare_subscribe_topics(
        hass=_hass,
        new_state=_state,
        topics=_topic,
    )
TypeError: async_prepare_subscribe_topics() got an unexpected keyword argument 'new_state'. Did you mean 'sub_state'?
```
## Additional information

I'm not able to understand if it is related to #79

**Comment by tofurky** [comment]
Left a note on #79 as well, but I just confirmed that changing the second `if` at custom_components/sleep_as_android/__init__.py at line 313 to `elif` seems to resolve the issue.
i.e.:
`elif self._ha_version >= AwesomeVersion("2022.3.0"):`

**Comment by Metus88** [comment]
> Left a note on #79 as well, but I just confirmed that changing the second `if` at custom_components/sleep_as_android/**init**.py at line 313 to `elif` seems to resolve the issue. i.e.: `elif self._ha_version >= AwesomeVersion("2022.3.0"):`

Thanks it works
